version: '3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env

  web:
    container_name: web
    build:
      context: ./srcs
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - app_django:/app/django
      - staticfiles:/var/www/static/
    env_file:
      - .env

  # nginx:
  #   container_name: nginx
  #   image: nginx
  #   restart: on-failure
  #   depends_on:
  #     - web
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - nginx_conf:/etc/nginx/conf.d/
  #     - staticfiles:/var/www/static/
  #   env_file:
  #     - .env

volumes:
  app_django:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/app
      o: bind
  nginx_conf:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/tools/nginx.conf
      o: bind
  staticfiles:
    driver: local
