version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env

  web:
    container_name: django
    build:
      context: ./srcs/web
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - web:/app/django
      - staticfiles:/var/www/static/
    env_file:
      - .env

  nginx:
    container_name: nginx
    build:
      context: ./srcs/nginx
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staticfiles:/var/www/static/
      - ./srcs/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-k", "https://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  web:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/web/app
      o: bind
  staticfiles:
    driver: local
