version: '3'
services:
  # db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: transcendance_db

  web:
    build:
      context: ./srcs/web
      dockerfile: Dockerfile
    restart: on-failure
    # depends_on:
    #   - db
    ports:
      - 8000:8000
    volumes:
      - ./srcs/web/app:/app/django
