version: '3'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env

  web:
    build:
      context: ./srcs/web
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./srcs/web/app:/app/django
    env_file:
      - .env

  nginx:
    build:
      context: ./srcs/nginx
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - web
    ports:
      - "0.0.0.0:8080:80"
    env_file:
      - .env
