version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env

  web:
    container_name: django
    build:
      context: ./srcs
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - app_django:/app/django
      - staticfiles:/var/www/static/
    env_file:
      - .env

volumes:
  app_django:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/app
      o: bind
  staticfiles:
    driver: local
