version: '3'
services:
  db:
    container_name: db
    image: postgres
    restart: always
    env_file:
      - .env

  web:
    container_name: web
    build:
      context: ./srcs
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - db
    volumes:
      - app_django:/app/django
      - staticfiles:/var/www/static/
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx
    restart: on-failure
    depends_on:
      - web
    ports:
      - "8000:443"
    volumes:
      - ./srcs/tools/ssl/transcendance.crt:/etc/nginx/ssl/transcendance.crt
      - ./srcs/tools/ssl/transcendance.key:/etc/nginx/ssl/transcendance.key
      - ./srcs/tools/nginx.conf:/etc/nginx/nginx.conf
      - staticfiles:/var/www/static/
    env_file:
      - .env

volumes:
  app_django:
    driver: local
    driver_opts:
      type: none
      device: ./srcs/app
      o: bind
  staticfiles:
    driver: local
